name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-deno-memory-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  test-deno-cookie-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STORE: cookie
      ENCRYPTION_KEY: password_at_least_32_characters_long
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  test-deno-kv-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STORE: kv
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  test-bun-sqlite-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      JS_RUNTIME: bun
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.2
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install --with-deps
    - name: Build NPM package for library
      run: deno run -A scripts/build_npm.ts
    - name: Install bun example server
      working-directory: ./test/bun
      run: bun install
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30